apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: hishampaloli/user
          env:
            - name: MONGO_URL
              value: "mongodb+srv://hishampaloli:hisham@user.rlulotn.mongodb.net/"
            - name: TWILIO_ACC_SID
              value: "ACc6812664b3f21c5c669509cff5764bb9"
            - name: TWILIO_TOKEN_AUTH
              value: "893178a26196fe093ab221691626b8de"
            - name: TWILIO_SERVICE_SID
              value: "VA5597e0ac8e160a7236be137d237e034e"
            - name: EMAIL_STR
              value: "perilla.hrservice@gmail.com"
            - name: PASSWORD_STR
              value: "cglzqvagkozftaco"
            - name: BUCKET_NAME
              value: "perilla"
            - name: ACCESS_KEY_ID
              value: "AKIAYUKL2MSDWO34MUNV"
            - name: PRIVATE_ACCESS_KEY_ID
              value: "dcdmaYKRtSA/GpZ5YAIRd3MiafTIVnz35Ky+BA/n"
            - name: REGION_KEY_ID
              value: "ap-south-1"
            - name: JWT_KEY
              value: "jisfjispfop"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 3000
