apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: hishampaloli/user
          env:
            - name: MONGO_URL
              value: "mongodb://user-mongo-srv:27017/user"
            - name: TWILIO_ACC_SID
              value: "ACc6812664b3f21c5c669509cff5764bb9"
            - name: TWILIO_TOKEN_AUTH
              value: "347f0415a4943579e19d559cac070fc4"
            - name: TWILIO_SERVICE_SID
              value: "VAaa5e73e6dda961a7ef66da4db67209ce"
            - name: EMAIL_STR
              value: "perilla.hrservice@gmail.com"
            - name: PASSWORD_STR
              value: "cglzqvagkozftaco"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 3000
